spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # ??? ????? ?? ??? ???? ??? ??
    # ??? ???? ??? API ???????? false? ??
    open-in-view: false
    # JPA ?? ?? ???? SQL? ??? ??? ?????.
    show-sql: true
      # hibernate ?? ??
    hibernate:
        # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
        # if exists drop table ??? ?? ?????? ?? ??.
        ddl-auto: update
    properties:
        hibernate:
          # ?? JPA? ???? Hibernate? ????? ???? SQL? ????? ?????.
          # ???? SQL? ???? ?? ???.
          format_sql: true
          default_batch_fetch_size: 500 # ??? ??? ?? ? ?? ???
